spring:
  application:
    name: core-paint
  datasource:
    url: jdbc:postgresql://localhost:5432/warpaintly
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
    default-schema: paints
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE


